apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: computeinstance-aliyun
  labels:
    vlimf.io/provider: aliyun
spec:
  compositeTypeRef:
    apiVersion: vlimf.io/v1alpha1
    kind: ComputeInstance

  resources:
    - name: ecsinstance
      base:
        apiVersion: ecs.alibaba.crossplane.io/v1alpha1
        kind: Instance
        spec:
          forProvider:
            regionId: cn-hangzhou
            instanceType: ecs.t5-lc2m1.nano
            imageId: ubuntu_20_04_x64_20G_alibase_20240222.vhd
            systemDisk:
              size: 20
          providerConfigRef:
            name: aliyun-provider
      patches:
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.regionId"
        - fromFieldPath: "spec.instanceType"
          toFieldPath: "spec.forProvider.instanceType"
        - fromFieldPath: "spec.diskSize"
          toFieldPath: "spec.forProvider.systemDisk.size"
        - fromFieldPath: "spec.osImage"
          toFieldPath: "spec.forProvider.imageId"
