apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: computeinstance-tencent
  labels:
    vlimf.io/provider: tencent
spec:
  compositeTypeRef:
    apiVersion: vlimf.io/v1alpha1
    kind: ComputeInstance

  resources:
    - name: cvminstance
      base:
        apiVersion: cvm.tencentcloud.crossplane.io/v1alpha1
        kind: Instance
        spec:
          forProvider:
            region: ap-guangzhou
            imageId: img-8toqc6s3
            instanceType: S5.MEDIUM4
            systemDisk:
              diskSize: 20
          providerConfigRef:
            name: tencent-provider
      patches:
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.instanceType"
          toFieldPath: "spec.forProvider.instanceType"
        - fromFieldPath: "spec.diskSize"
          toFieldPath: "spec.forProvider.systemDisk.diskSize"
        - fromFieldPath: "spec.osImage"
          toFieldPath: "spec.forProvider.imageId"
